// Embedded into the standalone demo. Propagation branches are generated by
// history_dynamics.py; only positive mixtures and classical readout run here.
Object.assign(TEXT.en, {
  dynamicsTitle:'Wavefunction and absorbing detector',
  dynamicsIntro:'A one-time upper/lower measurement changes the quantum state. The detector absorbs the evolving wave. Every record fades from its own creation time.',
  recordStartLabel:'Clock start / T₀', readoutWaitLabel:'Readout wait / σT',
  dynamicsScope:'Acquisition: 0–2 T₀; absorption rate: 4/T₀. Clock center = start + σT/α. The prepared wave has no earlier selection. λ controls the probability of selection. The keep/fade/β controls above set record lifetimes; observer age only moves the envelope cursor. κt belongs to the separate delay hypothesis below.',
  dynamicsNull:'Blue: no path selection', dynamicsPhysical:'Amber: physical detection', dynamicsSaved:'Pink: readable record',
  absorbedLabel:'physically detected', savedLabel:'readable click', erasedLabel:'erased record', missingLabel:'no record created',
  densityTitle:'Surviving quantum probability density', dynamicJointTitle:'Readable p(y,t), per preparation',
  jointAxes:'Horizontal: detection time 0–2 T₀. Vertical: detector position y.',
  dynamicsCaveat:'New candidate dynamics. Forgetting a classical record cannot undo the measurement back-action. The older delay heatmap below is a fixed benchmark from a different detector model.',
  frontCenter:'Front center', actualSelection:'Actual path selection', clockWindow:'Scheduled selection in gate',
  particleSurvival:'Surviving particle', densityChange:'density L1 change vs null',
  preparationNoRecord:'no record', preparationErased:'erased record', preparationSaved:'saved click',
  historySubtitle:'Proposed clock envelope; the causal instrument and measured probabilities are below',
  sceneNote:'Illustrative propagation. New event samples the dynamical detector law below.',
  newEvent:'New preparation',
  manualMarker:'manual position marker',
});
Object.assign(TEXT.fi, {
  dynamicsTitle:'Aaltofunktio ja absorboiva detektori',
  dynamicsIntro:'Kertaluonteinen ylemmän/alemman puoliskon mittaus muuttaa kvanttitilaa. Detektori absorboi etenevää aaltoa. Jokainen tietue vanhenee omasta syntymähetkestään.',
  recordStartLabel:'Kellon aloitus / T₀', readoutWaitLabel:'Lukuviive / σT',
  dynamicsScope:'Mittausikkuna: 0–2 T₀; absorptiotaajuus: 4/T₀. Kellon keskus = aloitus + σT/α. Valmistetulla aallolla ei ole aiempaa valintaa. λ määrää valinnan todennäköisyyden. Ylemmät säilytys-, häviämis- ja β-säätimet ohjaavat tietueiden elinikää; havaintoikä siirtää vain vaippakäyrän osoitinta. κt kuuluu alempaan erilliseen viivehypoteesiin.',
  dynamicsNull:'Sininen: ei puoliskon valintaa', dynamicsPhysical:'Keltainen: fysikaalinen osuma', dynamicsSaved:'Pinkki: luettava tietue',
  absorbedLabel:'fysikaalinen osuma', savedLabel:'luettava osuma', erasedLabel:'hävinnyt tietue', missingLabel:'ei syntynyttä tietuetta',
  densityTitle:'Jäljellä oleva kvanttitodennäköisyystiheys', dynamicJointTitle:'Luettava p(y,t) valmistusta kohden',
  jointAxes:'Vaaka: havaintoaika 0–2 T₀. Pysty: detektoripaikka y.',
  dynamicsCaveat:'Uusi dynamiikkahypoteesi. Klassisen tietueen unohtuminen ei kumoa mittauksen vaikutusta kvanttitilaan. Alempi vanha viivelämpökartta on toisen detektorimallin kiinteä vertailutulos.',
  frontCenter:'Rintaman keskus', actualSelection:'Toteutunut puoliskon valinta', clockWindow:'Ajoitettu valinta ikkunassa',
  particleSurvival:'Jäljellä oleva hiukkanen', densityChange:'tiheyden L1-muutos vertailusta',
  preparationNoRecord:'ei tietuetta', preparationErased:'hävinnyt tietue', preparationSaved:'tallennettu osuma',
  historySubtitle:'Ehdotettu kellovaippa; kausaalinen mittausmalli ja havaintotodennäköisyydet ovat alempana',
  sceneNote:'Havainnollinen eteneminen. Uusi tapahtuma arvotaan alemman dynaamisen detektorimallin mukaan.',
  newEvent:'Uusi valmistus',
  manualMarker:'käsin asetettu paikkamerkki',
});
state.recordStart=-2;
state.readoutWait=0;
let lastDynamics=null;

function logNormalTail(z) {
  // Central erf series; positive-tail Mills-ratio continued fraction avoids
  // subtraction of two nearly equal CDFs when preparation truncates a tail.
  const a=Math.abs(z);
  let logSmall;
  if(a>3) {
    let denominator=a;
    for(let n=160;n>=1;n--)denominator=a+n/denominator;
    logSmall=-a*a/2-Math.log(2*Math.PI)/2-Math.log(denominator);
  } else {
    const x=a/Math.sqrt(2);let term=x,total=x;
    for(let n=1;n<80;n++){term*=-x*x/n;total+=term/(2*n+1);}
    logSmall=Math.log(.5*(1-2/Math.sqrt(Math.PI)*total));
  }
  return z>=0?logSmall:Math.log1p(-Math.exp(logSmall));
}

function dynamicsWeights(center,sigma,strength) {
  const edges=DATA.historyDynamics.edges,q=-Math.expm1(-strength);
  const log0=logNormalTail((edges[0]-center)/sigma);
  const logs=edges.map(v=>logNormalTail((v-center)/sigma)-log0);
  const weights=logs.slice(0,-1).map((v,i)=>q*Math.exp(v)*(-Math.expm1(logs[i+1]-v)));
  weights.push(Math.exp(-strength)+q*Math.exp(logs.at(-1)));
  return weights;
}

function evaluateDynamics() {
  const d=DATA.historyDynamics,{sig,alpha}=current(),center=state.recordStart+sig/alpha;
  const weights=dynamicsWeights(center,sig,state.lambda), nt=d.times.length, ny=d.yBins;
  const ideal=Array.from({length:nt},()=>Array(ny).fill(0));
  const density=Array(d.densities[0].length).fill(0);
  for(let c=0;c<weights.length;c++) {
    const w=weights[c]; if(w===0)continue;
    for(let i=0;i<nt;i++)for(let j=0;j<ny;j++)ideal[i][j]+=w*d.clicks[c][i][j];
    for(let j=0;j<density.length;j++)density[j]+=w*d.densities[c][j];
  }
  const sum=a=>a.reduce((s,v)=>s+v,0), absorbed=sum(ideal.map(sum));
  const genuine=ideal.map(row=>d.blur.map(b=>d.efficiency*sum(b.map((v,j)=>v*row[j]))));
  const dark=(1-d.efficiency*absorbed)*d.darkProbability/(nt*ny);
  const readout=d.duration+state.readoutWait*sig;
  const survival=d.times.map(time=>Math.exp(-Math.pow(Math.max((readout-time)/sig-state.historyKeep,0)/state.historyFade,state.historyBeta)));
  const before=genuine.map(row=>row.map(v=>v+dark));
  const saved=before.map((row,i)=>row.map(v=>v*survival[i]));
  const savedMass=sum(saved.map(sum)), beforeMass=sum(before.map(sum));
  let stillPresent=1, selected=0;
  for(let i=0;i<nt;i++) {selected+=weights[i]*stillPresent;stillPresent-=sum(d.clicks.at(-1)[i]);}
  return {ideal,density,weights,center,absorbed,saved,before,savedMass,
    erased:beforeMass-savedMass,missing:1-beforeMass,surviving:sum(density),selected};
}

function paintRaster(id,flat,nx,ny,maxValue) {
  const {c,w,h}=setupCanvas($(id)); c.clearRect(0,0,w,h);
  for(let y=0;y<ny;y++)for(let x=0;x<nx;x++) {
    const v=Math.max(0,Math.min(1,flat[y*nx+x]/Math.max(maxValue,1e-30)));
    c.fillStyle=`hsl(${195+125*v} 85% ${6+65*Math.sqrt(v)}%)`;
    c.fillRect(x*w/nx,(ny-y-1)*h/ny,Math.ceil(w/nx),Math.ceil(h/ny));
  }
}

function drawDynamics() {
  const d=DATA.historyDynamics,r=evaluateDynamics();lastDynamics=r;
  const {c,w,h}=setupCanvas($('dynamicsChart')),left=48,right=w-16,top=25,bottom=h-34;
  const marginal=joint=>Array.from({length:d.yBins},(_,j)=>joint.reduce((s,row)=>s+row[j],0));
  const curves=[[marginal(d.clicks.at(-1)),'#63a6ff'],[marginal(r.ideal),'#ffcb6b'],[marginal(r.saved),'#ff6f9f']];
  const max=Math.max(1e-12,...curves.flatMap(([values])=>values));
  c.clearRect(0,0,w,h); drawAxes(c,w,h,'y bin','p / preparation');
  for(const [values,color] of curves) {
    c.beginPath();values.forEach((v,j)=>{const x=left+j*(right-left)/(d.yBins-1),y=bottom-v/max*(bottom-top);j?c.lineTo(x,y):c.moveTo(x,y)});
    c.strokeStyle=color;c.lineWidth=2;c.stroke();
  }
  c.fillStyle='#8fa7b6';c.fillText(max.toFixed(4),left+4,top);
  const percent=x=>(100*x).toFixed(2)+' %';
  $('dynamicsAbsorbed').textContent=percent(r.absorbed);
  $('dynamicsRecorded').textContent=percent(r.savedMass);
  $('dynamicsErased').textContent=percent(r.erased);
  $('dynamicsMissing').textContent=percent(r.missing);
  $('recordStartValue').textContent=state.recordStart.toFixed(2);
  $('readoutWaitValue').textContent=state.readoutWait.toFixed(2);
  $('dynamicsClock').textContent=`${t('frontCenter')}: ${r.center.toFixed(3)} T₀ · ${t('clockWindow')}: ${percent(1-r.weights.at(-1))} · ${t('actualSelection')}: ${percent(r.selected)}`;
  const difference=r.density.reduce((s,v,i)=>s+Math.abs(v-d.densities.at(-1)[i]),0);
  $('dynamicsTrace').textContent=`${t('particleSurvival')}: ${percent(r.surviving)} · ${t('densityChange')}: ${difference.toFixed(5)}. x →, y ↑`;
  paintRaster('dynamicsDensity',r.density,d.densityShape[1],d.densityShape[0],Math.max(...d.densities.at(-1),...r.density));
  const transposed=[];for(let j=0;j<d.yBins;j++)for(let i=0;i<d.times.length;i++)transposed.push(r.saved[i][j]);
  // Fixed per-control reference scale shows fading instead of normalizing it away.
  paintRaster('dynamicsJoint',transposed,d.times.length,d.yBins,Math.max(...r.before.flat()));
  drawMemoryBanks(r);
}

function sampleDynamicalPreparation() {
  const r=lastDynamics||evaluateDynamics(), d=DATA.historyDynamics;
  let u=Math.random(),event='preparationNoRecord',chosen=-1;
  for(let i=0;i<r.saved.length&&chosen<0;i++)for(let j=0;j<d.yBins;j++) {
    u-=r.saved[i][j];if(u<0){chosen=i*d.yBins+j;break;}
  }
  if(chosen>=0) {
    event='preparationSaved';state.eventY=48+(d.yBins-1-chosen%d.yBins)*334/(d.yBins-1);
    state.eventDelay=d.times[Math.floor(chosen/d.yBins)];
  } else {event=u<r.erased?'preparationErased':'preparationNoRecord';state.eventDelay=0;}
  state.eventLabel=event;state.eventResponds=chosen>=0;
  state.phase=0;state.playing=true;state.lastFrame=0;updateMotionLabel();updateWavefront();
}
['recordStart','readoutWait'].forEach(id=>$(id).addEventListener('input',e=>{state[id]=Number(e.target.value);drawDynamics()}));
